---
- name: Install ad-domain-service feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result
- name: Sets up the AD controller
  win_domain:
    dns_domain_name: "{{ad_domain_name}}"
    safe_mode_password: "{{ad_safe_mode_password}}"
  register: domainstate
- name: Reboots the instance after configuration
  win_reboot:
    msg: "Joining domain. Rebooting..."
    pre_reboot_delay: 10
  when: domainstate.reboot_required
- name: List Domain Controllers in domain
  win_shell: nltest /dclist:"{{ ad_domain_name }}"
  register: domain_list
- debug:
   var: domain_list
